name: myapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  image_picker: ^1.1.2
  http: ^1.2.2
  webview_flutter: ^2.0.10 
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1
  firebase_auth_web: ^5.13.2
  firebase_storage: ^12.3.4

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true