name: myapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  image_picker: ^1.1.2
  http: ^1.2.2
  webview_flutter: ^2.0.10 
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1
  firebase_auth_web: ^5.13.2
  firebase_storage: ^12.3.4
  flutter_sound: ^9.3.1
  just_audio: ^0.9.30
  permission_handler: ^10.2.0
  path_provider: ^2.1.5
  path: ^1.9.0
  speech_to_text: ^7.0.0
  audioplayers: ^6.1.0
  camera: ^0.11.0+2
  file_picker: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true